# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

networks:
  consul-network:

#Define services
services:
  consul:
    container_name: micro-services-consul
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - consul-network
    ports:
      - 8500:8500
      - 8600:8600

  traefik:
    build: ./traefik
    image: traefik-consul:latest
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - consul-network

  rabbitmq:
    container_name: micro-services-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      #      - rabbitmq-data-volume:/var/lib/rabbitmq
      #      - rabbitmq-log-volume:/var/log/rabbitmq
      - .docker/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-user}
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - consul-network
    ports:
      - ${MANAGEMENT_UI_HTTP_PORT:-8080}:15672
      - ${AMQP091_PORT:-5672}:5672
      - ${PROMETHEUS_PORT:-15692}:15692

  postgresdb:
    container_name: micro-services-postgres
    image: postgres
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - consul-network
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"

  api_commands:
    container_name: micro-services-commands-api
    build: .
    ports:
      - "8899:8899"
    volumes:
      - ./microservices:/api
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - consul-network
    restart: always

volumes:
  postgres:
