version: '3'
services:
  postgresdb:
    image: postgres
    container_name: micro-services-commands-postgres
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
  apicommands:
    image: esgimicroci/al1-commands:latest
    container_name: micro-services-commands-api
    ports:
      - "8899:8899"
    volumes:
     - al1commands:/var/api
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    restart: always

volumes:
  postgres:
  al1commands:
    external: true
