version: '3'
services:
  postgresdb:
    container_name: micro-services-postgresdb
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"

  api_commands:
    image: esgimicroci/al1-commands:latest
    container_name: micro-services-commands-api
    volumes:
      - ./microservices:/api
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    ports:
      - 8899:8899
    depends_on:
      - postgres
    restart: always

volumes:
  postgres:
