version: '3'
services:
  postgresdb:
    container_name: micro-services-postgres
    image: esgimicroci/al1-commands
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"

  api_commands:
    container_name: micro-services-commands-api
    image: esgimicroci/al1-commands
    ports:
      - "8899:8899"
    volumes:
      - ./microservices:/api
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    restart: always

volumes:
  postgres:
