version: '3'

services:
  postgresdb:
    image: postgres
    env_file:
      - keys.env
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
    restart: always
  apicommands:
    image: esgimicroci/al1-commands:latest
    container_name: micro-services-commands-api
    ports:
      - "8899:8899"
    expose:
      - 8899
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - commands-data:/api
    env_file:
      - keys.env
    restart: always

volumes:
  postgres:
  commands-data:
