version: '3'

networks:
  micro-commands-net:
    driver: bridge

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    networks:
      - micro-commands-net
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
    restart: always
  apicommands:
    image: esgimicroci/al1-commands:latest
    container_name: micro-services-commands-api
    ports:
      - "8899:8899"
    expose:
      - 8899
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - commands-data:/api
    networks:
      - micro-commands-net
    environment:
      - POSTGRES_DB=microservicesdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    restart: always

volumes:
  postgres:
  commands-data:
