version: '3'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"

  api_commands:
    image: esgimicroci/al1-commands:latest
    ports:
      - "8899:8899"
    volumes:
      - ./microservices:/api
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    depends_on:
      - postgresdb
    links:
      - postgresdb
    restart: always

volumes:
  postgres:
