version: '3'
services:
  api_commands:
    image: esgimicroci/al1-commands
    container_name: micro-services-commands-api
    working_dir: /api
    volumes:
      - ./microservices:/api
    command: >
      sh -c "mvn package &&
             java -jar /api/target/*.jar"
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    ports:
      - 8899:8899
    depends_on:
      - postgres
    restart: always

  postgres:
    image: esgimicroci/al1-commands
    container_name: micro-services-commands-postgres
    restart: always
    environment:
      - POSTGRES_DB=microservices_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1994
    ports:
      - 5432:5432
