name: ESGI Micro CI Commands

on: [push, pull_request]

jobs:
  build:
    name: Build Micro CI Commands Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Build Project
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: cd ./microservices/ && mvn install && mvn -B package --file pom.xml

      - name: Test Project
        run: ls ./microservices/target/

  deploy:
    name: Build/Publish Docker Images to DockerHub & Deploy to Azure VM
    runs-on: ubuntu-latest
    #    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: esgimicroci/al1-commands
          tag_with_ref: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke -g ${{ secrets.AZURE_RESOURCE_GRP }} -n ${{ secrets.AZURE_VM }} --command-id RunShellScript --scripts "cd /home/micro-ci-al1/micro-ci-commands && wget -q https://raw.githubusercontent.com/esgi-microservices-al1/micro-ci-commands/workflow/.github/azure/docker-compose.yml -O docker-compose.yml && docker-compose stop && docker-compose pull docker-compose rm -f && docker-compose up -d"
